pagy:
  product:
    page_8: 8
    per_page: 9
  bill:
    per_page: 5
  order:
    per_page: 8
  user:
    per_page: 8
  banner:
    per_page: 5
col:
  col_4: 4
  col_3: 3
cart:
  size:
    default: 0
    min: 1
  increment:
    condition: "true"
    default: 1
  decrement:
    default: -1
bill:
  amount:
    min: 0
  payment_method:
    max_length: 255
  status:
    completed: 1
order:
  status:
    all: "all"
    pending: "pending"
    canceled: "canceled"
    completed: "completed"
    confirmed: "confirmed"
    delivering: "delivering"
  action:
    cancel: "cancel"
    confirm: "confirm"
    delivery: "delivery"
    complete: "complete"
    delete: "delete"
product_detail:
  price_0: 0
  price_20: 20
  price_50: 50
  price_100: 100
  price_max: 1000000
search_type:
  name: "name"
  category: "category"
  brand: "brand"
product:
  product_top: 8
  order_ASC: "ASC"
  order_DESC: "DESC"
  increment:
    condition_true: "true"
    condition_false: "false"
  status:
    all: "all"
    active: "active"
    inactive: "inactive"
account:
  role:
    title: "role"
  status:
    title: "status"
banner:
  state:
    active: "active"
    inactive: "inactive"
    all: "all"
