pagy:
  product:
    per_page: 9
cart:
  size:
    default: 0
    min: 1
  increment:
    condition: "true"
    default: 1
  decrement:
    default: -1
bill:
  amount:
    min: 0
  payment_method:
    max_length: 255
