// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./js/bootstrap.min"
import "./js/jquery.countdown.min"
import "./js/jquery.magnific-popup.min"
import "./js/jquery.nice-select.min"
import "./js/jquery.nicescroll.min"
import "./js/jquery.slicknav"
import "./js/jquery-3.3.1.min"
import "./js/main"
import "./js/mixitup.min"
import "./js/owl.carousel.min"
